### ISSUE TITLE
Legtrack debug flag doesn't work

### ISSUE THREAD

**Issue by rwakida** [HACC2022/data#1]
The scraper code throws the following error when the debug argument is true. 
```
>:/tmp/Legtrack# php -f scrape-measures.php development 2022 true
Trying to connect to captiol
PHP Fatal error:  Uncaught Error: Call to undefined function legtrack\setDebugOptions() in /tmp/Legtrack/lib/curl.php:72
Stack trace:
#0 /tmp/Legtrack/lib/curl.php(36): legtrack\Curl->download()
#1 /tmp/Legtrack/scrape-measures.php(96): legtrack\Curl->getMeasures()
#2 /tmp/Legtrack/scrape-measures.php(164): legtrack\checkCapitolSiteUpdate()
#3 {main}
  thrown in /tmp/Legtrack/lib/curl.php on line 72
```
To duplicate run:

php -f scrape-measures.php development 2022 true
```

**Comment by rwakida** [comment]
@keokilee I don't have permission to create a new branch in this repo so I couldn't create a pull request.  As a workaround,  I forked this repo and pushed the fix there.  Please see: [Fix in forked repo](https://github.com/rwakida/hacc2022-data/commit/a408085019d0568c55defe49993b54ca2f1bee33)
